depends "apt"
depends "postgresql"
depends "rvm"
depends "vim"
maintainer       "reenhanced"
maintainer_email "nhance@reehanced.com"
license          "All rights reserved"
description      "Installs/Configures prototype_app"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
